Update networks supported by core services
safe-global/safe-docs pull request #178
Opened 2023-03-09 22:01 UTC by KevinLu

Rinkeby is no longe supported by Safe.

2023-03-10 13:51 UTC, ademidun approved these changes
Thanks for starting this PR @KevinLu .

I also used this opportunity to piggyback on some other changes as well.

2023-03-10 16:02 UTC, Uxio0 requested changes

2023-03-10 16:02 UTC, Uxio0 commented on learn/infrastructure/service-architecture.md
>  The client gateway leverages the config services to determine how to reach the core service instance required for a given request. If the network is supported (which is determined by the config servi
transforms (and sometimes aggregates) -> `transforms, aggregates and caches information from Config Service and Transaction Service, optimizing data for our web and mobile clients`

2023-03-10 18:29 UTC, KevinLu commented on learn/infrastructure/service-architecture.md
> +The Safe infrastracture consists of 3 services:
Did you want to fix this typo?

2023-03-10 18:40 UTC, KevinLu commented on learn/infrastructure/service-architecture.md
>  The config services keeps track of all the networks we support and therefore of all the instances of the core services that are available. In addition to this, the config service provides information
Agreed.

2023-03-13 13:36 UTC, Uxio0 approved these changes

2023-03-22 13:29 UTC, ademidun commented on learn/infrastructure/service-architecture.md
> +The transaction services use event indexing to keep track of transactions related to our safe contracts. There is one instance of the core services per supported network (mainnet, goerli, gnosis chai
I thought Goerli uses event indexing?  cc @mmv08 

[This Safe](https://app.safe.global/home?safe=gor:0xb67bF8d736b7024eaE034Fc0fBe80625823a6b76) was created on Goerli and uses [`GnosisSafeL2`](https://github.com/safe-global/safe-contracts/blob/main/contracts/SafeL2.sol#L7) as it's [contract implementation address](https://goerli.etherscan.io/address/0x3E5c63644E683549055b9Be8653de26E0B4CD36E).

See [contract creation hash](https://goerli.etherscan.io/tx/0x1bbb14cf468099c16796cebb07cf2dbb0df438f0e9a06e4fe8e56688c4e3a8d8).

[GnosisSafeL2 emits a `SafeMultiSigTransaction` Event](https://github.com/safe-global/safe-contracts/blob/186a21a74b327f17fc41217a927dea7064f74604/contracts/GnosisSafeL2.sol#L56) unlike [GnosisSafe.sol](https://github.com/safe-global/safe-contracts/blob/186a21a74b327f17fc41217a927dea7064f74604/contracts/GnosisSafe.sol).

2023-03-22 13:37 UTC, mmv08 commented on learn/infrastructure/service-architecture.md
> +The transaction services use event indexing to keep track of transactions related to our safe contracts. There is one instance of the core services per supported network (mainnet, goerli, gnosis chai
I believe it supports both technically, but the interface uses the tracing implementation by default.

2023-03-22 13:40 UTC, mmv08 commented on learn/safe-core-api/available-services.md
> -| Energy Web Chain             | [https://safe-transaction-ewc.safe.global/](https://safe-transaction-ewc.safe.global/)                   |
We will be discontinuing our UI and API support for Energy Web Chain and Volta on Wednesday, March 22nd, 2023. If you have any questions or concerns, please reach out to the EWC team who will provide alternative support.

2023-03-22 19:45 UTC, KevinLu commented
@ademidun I've resolved the conflict

2023-03-23 12:09 UTC, merged

2023-03-23 12:27 UTC, Uxio0 commented on learn/infrastructure/service-architecture.md
> +The transaction services use event indexing to keep track of transactions related to our safe contracts. There is one instance of the core services per supported network (mainnet, goerli, gnosis chai
For Goerli we use tracing, to have a testing environment similar to mainnet. Services using trace indexing are able to see both L2 and regular Safes