Add safe transaction service documentation
safe-global/safe-docs pull request #235
Opened 2023-09-21 12:03 UTC by moisses89

The idea of this PR is add more relevant documentation about safe transaction service based on users/developers questions. 
This PR is adding: 
- an overview of transaction service
- key features of transaction service
- off-chain signatures documentation

2023-09-26 10:32 UTC, Uxio0 approved these changes
Really nice work

2023-09-27 08:26 UTC, tanay1337 requested changes
Thanks a lot, @moisses89!

2023-09-27 08:26 UTC, tanay1337 commented on safe-core-api/safe-transaction-service.md
> +## Offchain transaction signatures
```suggestion
## Offchain Transaction Signatures
```

2023-09-27 08:26 UTC, tanay1337 commented on safe-core-api/safe-transaction-service.md
> +The transaction service can collect off-chain transaction signatures, allowing the owners to share their signatures between them to reach the required threshold before execute a transaction and spend
```suggestion
The transaction service can collect offchain transaction signatures, allowing the owners to share their signatures to reach the required threshold before executing a transaction and spending less gas than onchain approvals.
```

2023-09-27 08:26 UTC, tanay1337 commented on safe-core-api/safe-transaction-service.md
> +The following endpoints let us to propose a transaction and collect every confirmation (off-chain signatures):
```suggestion
The following endpoints let us propose a transaction and collect every confirmation (offchain signatures):
```

2023-09-27 08:26 UTC, tanay1337 commented on safe-core-api/safe-transaction-service.md
> +- `POST /v1/safes/{address}/multisig-transactions/` create a new transaction, at least one signature is required
```suggestion
- `POST /v1/safes/{address}/multisig-transactions/`: Create a new transaction. At least one signature is required.
```

2023-09-27 08:26 UTC, tanay1337 commented on safe-core-api/safe-transaction-service.md
> +- `POST /v1/multisig-transactions/{safe_tx_hash}/confirmations/` add a new confirmation, the `safe_tx_hash` is needed
```suggestion
- `POST /v1/multisig-transactions/{safe_tx_hash}/confirmations/`: Add a new confirmation. The `safe_tx_hash` is needed.
```

2023-09-27 08:26 UTC, tanay1337 commented on safe-core-api/safe-transaction-service.md
> +- `GET /v1/multisig-transactions/{safe_tx_hash}/` return all the multisig-transaction information
```suggestion
- `GET /v1/multisig-transactions/{safe_tx_hash}/`: Return all the multisig transaction information.
```

2023-09-27 08:26 UTC, tanay1337 commented on safe-core-api/safe-transaction-service.md
> +- `GET /v1/multisig-transactions/{safe_tx_hash}/confirmations/` return the list of all confirmations to a multisig-transaction
```suggestion
- `GET /v1/multisig-transactions/{safe_tx_hash}/confirmations/`: Return the list of all confirmations to a multisig transaction.
```

2023-09-27 08:26 UTC, tanay1337 commented on safe-core-api/safe-transaction-service.md
> +The following sequence diagram shows an use case from a Safe shared by Alice and Bob where at least 1 confirmation for each one is required:
```suggestion
The following sequence diagram shows a use case for a Safe shared by Alice and Bob where at least one confirmation for each one is required:
```

2023-09-27 08:26 UTC, tanay1337 commented on safe-core-api/safe-transaction-service.md
> +`safe_tx_hash` is the unique identifier for a safe transaction and is calculated following [EIP-712](https://eips.ethereum.org/EIPS/eip-712) standard:
```suggestion
`safe_tx_hash` is the unique identifier for a Safe transaction and is calculated using the [EIP-712](https://eips.ethereum.org/EIPS/eip-712) standard:  
```

2023-09-27 08:26 UTC, tanay1337 commented on safe-core-api/safe-transaction-service.md
> +where `safeTxHashStruct` is the hashStruct of a safe transaction.
```suggestion
where `safeTxHashStruct` is the hashStruct of a Safe transaction.
```

2023-09-27 08:26 UTC, tanay1337 commented on safe-core-api/safe-transaction-service.md
> +## Offchain messages
```suggestion
## Offchain Messages 
```

2023-09-27 08:26 UTC, tanay1337 commented on safe-core-api/safe-transaction-service.md
> +Safe transaction service is able to collect the necessary offchain signatures to confirm a message  following [EIP1271](https://ethereum.org/pt/developers/tutorials/eip-1271-smart-contract-signatures
```suggestion
Safe transaction service can collect the necessary offchain signatures to confirm a message using [EIP-1271](https://ethereum.org/pt/developers/tutorials/eip-1271-smart-contract-signatures/#example-eip-1271-implementation-safe).    
```

2023-09-27 08:26 UTC, tanay1337 commented on safe-core-api/safe-transaction-service.md
> +The message can be a string (EIP-191 is used to get the hash) or an object EIP-712.
```suggestion
The message can be a string (EIP-191 is used to get the hash) or an object EIP-712.
```

2023-09-27 08:26 UTC, tanay1337 commented on safe-core-api/safe-transaction-service.md
> +- `GET /v1/safes/{address}/messages/` return the messages created for given safe address.
```suggestion
- `GET /v1/safes/{address}/messages/`: Return the messages created for the given Safe address.
```

2023-09-27 08:26 UTC, tanay1337 commented on safe-core-api/safe-transaction-service.md
> +- `POST /v1/safes/{address}/messages/` create a message with at least one signature
```suggestion
- `POST /v1/safes/{address}/messages/`: Create a message with at least one signature.
```

2023-09-27 08:26 UTC, tanay1337 commented on safe-core-api/safe-transaction-service.md
> +- `GET /v1/messages/{message_hash}/`  return a message for a given message hash
```suggestion
- `GET /v1/messages/{message_hash}/`: Return a message for a given message hash.
```

2023-09-27 08:26 UTC, tanay1337 commented on safe-core-api/safe-transaction-service.md
> +- `POST /v1/messages/{message_hash}/signatures/` add another signature to message with given message hash
```suggestion
- `POST /v1/messages/{message_hash}/signatures/`: Add another signature to the message with the given message hash.
```

2023-09-27 08:26 UTC, tanay1337 commented on safe-core-api/safe-transaction-service.md
> +The following sequence diagram shows an use case from a Safe shared by Alice and Bob where at least 1 signature for each one is required to fully confirm a message:
```suggestion
The following sequence diagram shows a use case for a Safe shared by Alice and Bob where at least one signature for each one is required to confirm a message fully:
```

2023-09-27 08:26 UTC, tanay1337 commented on safe-core-api/safe-transaction-service.md
> +Safe transaction service is able to decode contract interactions, to achive it, the service is periodically getting source and ABI's from different sources (Sourcify, etherscan and blockscout) using
```suggestion
The Safe transaction service can decode contract interactions. To achieve it, the service periodically gets source and ABIs from different sources like Sourcify, etherscan, and blockscout using the `safe-eth-py` library.   
```

2023-09-27 08:26 UTC, tanay1337 commented on safe-core-api/safe-transaction-service.md
> +The detection of contract interactions is done in a periodic task that is executed every hour for `multisig-transaction` and `module-transactions` or every 6 hours for `multisend-transactions` on `wo
```suggestion
The detection of contract interactions is done in a periodic task executed every hour for `multisig-transaction` and `module-transactions` or every six hours for `multisend-transactions` on `worker-contracts-tokens`.
```

2023-09-27 08:26 UTC, tanay1337 commented on safe-core-api/safe-transaction-service.md
> +For every new contract the service try to download the source and the ABI requesting it first to `soucify`, then `etherscan` and as last chance `blockscout`. It's important to know that not all this
```suggestion
For every new contract, the service tries to download the source, and the ABI requests it first to Sourcify, then Etherscan, and as a last chance, Blockscout. It's important to know that not all these data sources are supported or configured for every network on `safe-eth-py`.   
```

2023-09-27 08:26 UTC, tanay1337 commented on safe-core-api/safe-transaction-service.md
> +## Transactions decode
```suggestion
## Transaction Decoder
```

2023-09-27 09:57 UTC, moisses89 commented on safe-core-api/safe-transaction-service.md
> +- [**Blockchain Indexing**]() executed transactions, configuration changes, erc20/721 transfers, onchain confirmations… are automatically indexed from blockchain.
I'll add blockchain indexing in other PR.

2023-09-27 10:06 UTC, tanay1337 commented on safe-core-api/safe-transaction-service.md
> +- [**Blockchain Indexing**]() executed transactions, configuration changes, erc20/721 transfers, onchain confirmations… are automatically indexed from blockchain.
Gotcha, thanks! 🙌

2023-09-27 13:02 UTC, tanay1337 approved these changes
Thank you so much!

2023-09-27 13:02 UTC, merged