Add safe transaction indexing section
safe-global/safe-docs pull request #236
Opened 2023-09-28 10:09 UTC by moisses89

2023-09-28 11:54 UTC, Uxio0 requested changes

2023-09-28 11:54 UTC, Uxio0 commented on safe-core-api/safe-transaction-service.md
> +For L1 chains the indexer call tracing methods, for oldest blocks [trace_filter](https://openethereum.github.io/JSONRPC-trace-module#trace_filter) is used filtered by singleton address of safe contra
```suggestion
For L1 chains the indexer calls tracing methods, for oldest blocks [trace_filter](https://openethereum.github.io/JSONRPC-trace-module#trace_filter) is used filtering by singleton address of Safe contracts and for latest blocks [trace_block](https://openethereum.github.io/JSONRPC-trace-module#trace_block) is used, as `trace_filter` takes longer to return updated information. `trace_block` will be used if the block depth is lower than `ETH_INTERNAL_TXS_NUMBER_TRACE_BLOCKS`. The environment variables used by indexing are defined [here](https://github.com/safe-global/safe-transaction-service/blob/master/config/settings/base.py#L433). 
```

2023-09-28 11:54 UTC, Uxio0 commented on safe-core-api/safe-transaction-service.md
> +From safe creation the transaction service is storing each contract change on `SafeStatus` model as nonce, owners... and the last current status of a Safe in `SafeLastStatus`.
```suggestion
From Safe creation the transaction service is storing each contract change on `SafeStatus` model as `nonce`, `owners`... and the last current status of a Safe in `SafeLastStatus`, for database easy access and optimization.
```

2023-09-28 11:54 UTC, Uxio0 commented on safe-core-api/safe-transaction-service.md
> +**Reorgs handling**
```suggestion
### Reorgs handling  
```

2023-09-28 11:54 UTC, Uxio0 commented on safe-core-api/safe-transaction-service.md
> +When indexed every block is marked as not confirmed unless it has some depth (configured via ETH_REORG_BLOCKS environment variable). Not confirmed blocks are checked periodically to check if the bloc
```suggestion
Every block is marked as `not confirmed` during indexing unless it has some depth (configured via `ETH_REORG_BLOCKS` environment variable). Not confirmed blocks are checked periodically to check if the blockchain `blockHash` for that number changed before it reaches the desired number of confirmations, if that's the case, all blocks from that block and the transactions related are deleted and indexing is restarted to the last confirmed block.

**Note:** No offchain signatures, transactions or messages are lost on this process. Only onchain data is removed.
```

2023-09-28 11:54 UTC, Uxio0 commented on safe-core-api/safe-transaction-service.md
>  The transaction service can collect offchain transaction signatures, allowing the owners to share their signatures to reach the required threshold before executing a transaction and spending less gas
```suggestion
Safe Transaction Service can collect offchain transaction signatures, allowing the owners to share their signatures to reach the required threshold before executing a transaction and spending less gas than onchain approvals.
```

2023-09-29 12:36 UTC, Uxio0 commented
Closes https://github.com/safe-global/safe-transaction-service/issues/1655

2023-10-02 07:15 UTC, tanay1337 requested changes
Nicely done, @moisses89 🥂

2023-10-02 07:15 UTC, tanay1337 commented on safe-core-api/safe-transaction-service.md
> +Every block is marked as `not confirmed` during indexing unless it has some depth (configured via `ETH_REORG_BLOCKS` environment variable). Not confirmed blocks are checked periodically to check if t
```suggestion
Every block is marked as `not confirmed` during indexing unless it has some depth (configured via the `ETH_REORG_BLOCKS` environment variable). Unconfirmed blocks are checked periodically to see if the blockchain `blockHash` for that number changed before it reaches the desired number of confirmations. If that's the case, all blocks from that block and related transactions are deleted, and indexing is restarted to the last confirmed block.
```

2023-10-02 07:15 UTC, tanay1337 commented on safe-core-api/safe-transaction-service.md
> +**Note:** No offchain signatures, transactions or messages are lost on this process. Only onchain data is removed.
```suggestion
**Note:** No offchain signatures, transactions, or messages are lost in this process. Only onchain data is removed.
```

2023-10-05 07:18 UTC, tanay1337 approved these changes

2023-10-05 07:19 UTC, merged