docs: fix typos
safe-global/safe-docs pull request #271
Opened 2023-11-06 08:20 UTC by xiaolou86

2023-11-06 10:05 UTC, louis-md approved these changes

2023-11-08 11:23 UTC, germartinez requested changes

2023-11-08 11:23 UTC, germartinez commented on safe-apps/release.md
> +We also would like to make a rough functional review of the App, so please provide us with a high-level test plan/feature list that allows our QA team to ensure everything works as intended in produc
```suggestion
We also would like to make a rough functional review of the App, so please provide us with a high-level test plan/feature list that allows our QA team to ensure everything works as intended in production. Video walkthroughs are also welcome.
```

2023-11-08 11:23 UTC, germartinez commented on safe-core-api/rpc-requirements.md
> +* If request takes **less than 3 seconds**, number of blocks to process are incremented by a small amount (currently 20).
```suggestion
* If the request takes **less than 3 seconds**, the number of blocks to process is incremented by a small amount (currently 20).
```

2023-11-08 11:23 UTC, germartinez commented on safe-core-api/rpc-requirements.md
>  * If request takes **less than 1 second**, node can process more. Number of blocks to fetch is duplicated for the next request.
```suggestion
* If the request takes **less than 1 second**, the node can process more. The number of blocks to fetch is duplicated for the next request.
```

2023-11-08 11:23 UTC, germartinez commented on safe-core-api/rpc-requirements.md
> +* If request takes **more than 20 seconds**, number of blocks to process are decremented by a small amount (currently 20).
```suggestion
* If the request takes **more than 20 seconds**, the number of blocks to process is decremented by a small amount (currently 20).
```

2023-11-08 11:23 UTC, germartinez commented on safe-core-api/rpc-requirements.md
>  * If request takes **more than 30 seconds**, number of blocks to process are halved.
```suggestion
* If the request takes **more than 30 seconds**, the number of blocks to process is halved.
```

2023-11-08 11:23 UTC, germartinez commented on safe-apps/release.md
> +When a user opens the app, it should automatically select the Safe as a wallet. Ensure to check the case if the user previously opened the app outside the Safe with another wallet.
```suggestion
When a user opens the app, it should automatically select the Safe as a wallet. Ensure to check the case if the user previously opened the app outside of the Safe with another wallet.
```

2023-11-09 02:19 UTC, xiaolou86 commented
@germartinez Thanks for your review.

2023-11-13 14:57 UTC, merged