Signatures using the Core SDK
safe-global/safe-docs pull request #318
Opened 2024-01-25 04:43 UTC by germartinez

## Context:
The SDK team is updating the documentation to explain how to create signatures using the Safe{Core} SDK:
- Utilities to generate signatures using the SDK
- Signature collection to execute Transactions or to sign Messages
- Signature collection using the SDK and Safe Services
- on-chain vs off-chain messages

## Note:
This PR cherry picks all the commits from https://github.com/safe-global/safe-docs/pull/313 as that PR was created from the wrong base branch. This one is using `development` after `nextra` was squash merged.

2024-01-25 12:08 UTC, germartinez commented on pages/sdk-protocol-kit/guides/safe-signatures.md
> +Your Safe Account can be configured with various thresholds and different owner types. An owner can be any Ethereum address, such as:
```suggestion
Your Safe account can be configured with different values for the threshold and different types of owner. An owner can be any Ethereum address, such as:
```

2024-01-25 12:08 UTC, germartinez commented on pages/sdk-protocol-kit/guides/safe-signatures.md
> +- An smart contract that implements [EIP-1271](https://eips.ethereum.org/EIPS/eip-1271) for signature validation, such as Safe Account
```suggestion
- An smart contract that implements [EIP-1271](https://eips.ethereum.org/EIPS/eip-1271) for signature validation, such as another Safe.
```

2024-01-25 12:08 UTC, germartinez commented on pages/sdk-protocol-kit/guides/safe-signatures.md
> +In this article, we will use the following Safe Account setup. We've five different Ethereum addresses that can act as signers, namely _owner1_ to _owner5_.
```suggestion
In this article, we will use the following Safe account setup. We've five different Ethereum addresses that can act as signers, namely `owner1` to `owner5`.
```

2024-01-25 12:08 UTC, germartinez commented on pages/sdk-protocol-kit/guides/safe-signatures.md
> +| **safeAddress3_4** | 0xb3b3862D8e38a1E965eb350B09f2167B2371D652 |
```suggestion
| **safe3_4** | 0xb3b3862D8e38a1E965eb350B09f2167B2371D652 |
```

2024-01-25 12:08 UTC, germartinez commented on pages/sdk-protocol-kit/guides/safe-signatures.md
> +  safeAddress: safeAddress3_4,
```suggestion
  safeAddress: safe3_4,
```

2024-01-25 12:09 UTC, germartinez commented
Acording to the code style in the docs all semicolons should be removed.

2024-01-25 13:55 UTC, yagopv commented
@germartinez all the suggestions and comments were addressed

2024-01-31 13:51 UTC, yagopv approved these changes

2024-02-13 08:01 UTC, tanay1337 requested changes

2024-02-13 08:01 UTC, tanay1337 commented on pages/sdk-protocol-kit/guides/signatures/transactions.mdx
> +The `getTransaction` method returns the transaction with the `confirmations` property, used to check all the signatures that were added.
```suggestion
The `getTransaction` method returns the transaction with the `confirmations` property to check all the added signatures.
```

2024-02-13 08:01 UTC, tanay1337 commented on pages/sdk-protocol-kit/guides/signatures/transactions.mdx
> +Connect the Safe and the adapter of an owner to the Protocol Kit. Ensure there are enough funds available in the owner's account to execute the transaction and cover the gas costs. Once the Protocol
```suggestion
Connect the Safe and the adapter of an owner to the Protocol Kit. Ensure enough funds are available in the owner's account to execute the transaction and cover the gas costs. Once the Protocol Kit is initialized, the `executeTransaction` method receives and executes the transaction with the required signatures.
```

2024-02-13 10:22 UTC, tanay1337 approved these changes

2024-02-13 11:12 UTC, merged