feat: add Safe CLI docs
safe-global/safe-docs pull request #400
Opened 2024-03-15 09:25 UTC by tanay1337

2024-03-22 13:32 UTC, germartinez requested changes

2024-03-22 14:40 UTC, louis-md approved these changes
Looks great to me!

2024-03-22 14:40 UTC, louis-md commented on pages/advanced/cli-installation.mdx
> +Safe CLI can be run using [Docker](https://www.docker.com) and [pip](https://pip.pypa.io/en/stable).
```suggestion
Safe CLI can be run using [Docker](https://www.docker.com) or [pip](https://pip.pypa.io/en/stable).
```

2024-03-22 23:43 UTC, germartinez requested changes
It looks like the content was not revised, only formatted. All the content should be checked with Grammarly and read again before merging it. I left some comments/suggestions, but I guess there are more.

2024-03-22 23:43 UTC, germartinez commented on pages/advanced/cli-reference/tx-service-operations.mdx
> +Sign a transaction with the loaded owners for the provided `SafeTxHash`.
```suggestion
Sign a transaction with the loaded owners for the provided Safe transaction hash.
```

2024-03-22 23:43 UTC, germartinez commented on pages/advanced/cli-reference/tx-service-operations.mdx
> +Sign the provided string message provided by standard input or the `EIP712` provided by file.
```suggestion
Sign the provided string message provided by standard input or the `EIP-712` provided by file.
```

2024-03-22 23:43 UTC, germartinez commented on pages/advanced/cli-reference/tx-service-operations.mdx
> +Sign the provided string message provided by standard input or the `EIP712` provided by file.
"Provided" appears 3 times in this sentence

2024-03-22 23:43 UTC, germartinez commented on pages/advanced/cli-reference/tx-service-operations.mdx
> +Batch transactions into one Multisig transaction using the provided `safe-nonce.` Any safe-tx can be used, like transactions from other Safes, already executed transactions, pending execution, etc. T
```suggestion
Batch transactions into one multi-signature transaction using the provided `safe-nonce.` Any `safe-tx` can be used, like transactions from other Safe accounts, already executed transactions, pending execution, etc. The only limitation is that the *transactions from other networks cannot be used*. The batching order will follow the same order of the `safe-tx-hashes` provided.
```

2024-03-22 23:43 UTC, germartinez commented on pages/advanced/cli-reference/tx-service-operations.mdx
> +Returns a list of *delegates* for the Safe. A *delegate* can be used when you *trust an address to post transactions to the tx-service on your behalf*. If a transaction is not trusted (posted to the
For consistency, italics is not the right format for this, we don't use them anywhere else in the docs. They appear not only here, but in different places in the CLI docs.

2024-03-22 23:43 UTC, germartinez commented on pages/advanced/cli-reference/common-operations.mdx
> +Run the Safe-CLI, then:
Safe CLI

2024-03-22 23:43 UTC, germartinez commented on pages/advanced/cli-reference/common-operations.mdx
> +If the information in the information bar is outdated or there's any problem, you can force the `safe-cli` to update the information about the Safe.
```suggestion
If the information in the information bar is outdated or there's any problem, you can force the Safe CLI to update the information about the Safe.
```

2024-03-22 23:43 UTC, germartinez commented on pages/advanced/cli-reference/common-operations.mdx
> +## Update guard
Use "Safe Guard" in this title and description

2024-03-22 23:43 UTC, germartinez commented on pages/advanced/cli-guides/recovery-safe-deployment.mdx
> +
```suggestion
```

2024-03-22 23:43 UTC, germartinez commented on pages/advanced/cli-demos.mdx
> +## Sending Ether using a Trezor hardware wallet
For consistency, the infinitive form should be used instead of the gerund (same in the link)

2024-03-22 23:43 UTC, germartinez commented on pages/advanced/cli-demos.mdx
> +## Create a remove owner transaction in the Transaction Service
This sounds artificial. Maybe: "Create a transaction in the Safe Transaction Service to remove an owner". Same in the link

2024-03-22 23:43 UTC, germartinez commented on pages/advanced/cli-reference/common-operations.mdx
> +Updates the Safe to the latest version (if you are on a known network like `Goerli` or `Mainnet`).
Check if we use Mainnet or `Mainnet` in our docs

2024-03-22 23:43 UTC, germartinez commented on pages/advanced/cli-reference/common-operations.mdx
> +## Update to L2
It is not clear what is been updated

2024-03-22 23:43 UTC, germartinez commented on pages/advanced/cli-reference/common-operations.mdx
> +### Remove an owner
There are inconsistencies here:
- Remove **an** owner
- Change (the) threhold
- Enable (a) module
- Etc.

2024-03-22 23:43 UTC, germartinez commented on pages/advanced/cli-reference/common-operations.mdx
> +To enable, the Safe CLI must be installed as follows:
It's not clear what the reader needs to enable

2024-03-22 23:43 UTC, germartinez commented on pages/advanced/cli-reference/common-operations.mdx
> +The Ledger module is an optional feature of Safe CLI to sign transactions with the help of [ledgereth](https://github.com/mikeshultz/ledger-eth-lib) library based on [ledgerblue](https://github.com/L
Is it "Safe CLI" or "the Safe CLI"? This happens a lot of times in the CLI docs

2024-03-22 23:43 UTC, germartinez commented on pages/advanced/cli-reference/common-operations.mdx
> +- `load_ledger_cli_owners [--legacy-accounts] [--derivation-path <str>]`: show a list of the first five accounts (--legacy-accounts search using legacy derivation) or load an account from provided de
```suggestion
- `load_ledger_cli_owners [--legacy-accounts] [--derivation-path <str>]`: shows a list of the first five accounts (`--legacy-accounts` search using legacy derivation) or loads an account from the provided derivation path.
```

2024-03-22 23:43 UTC, germartinez commented on pages/advanced/cli-reference/common-operations.mdx
> +- `load_trezor_cli_owners [--legacy-accounts] [--derivation-path <str>]`: show a list of the first five accounts (--legacy-accounts search using legacy derivation) or load an account from provided de
```suggestion
- `load_trezor_cli_owners [--legacy-accounts] [--derivation-path <str>]`: shows a list of the first five accounts (`--legacy-accounts` search using legacy derivation) or loads an account from provided derivation path.
```

2024-03-22 23:43 UTC, germartinez commented on pages/advanced/cli-reference/common-operations.mdx
> +If the information in the information bar is outdated or there's any problem, you can force the `safe-cli` to update the information about the Safe.
Is not clear what the "information bar" is

2024-03-22 23:46 UTC, germartinez commented on pages/advanced/cli-guides/recovery-safe-deployment.mdx
> +# Recovery Safe Deployment
I'm not sure this title (same in the sidebar) is descriptive enough.

2024-03-22 23:49 UTC, germartinez commented on pages/advanced/cli-reference/common-operations.mdx
> +  You must first load the sender's private key. When loading an owner, it will be set automatically.
This does not give context on why, where, and how

2024-03-22 23:50 UTC, germartinez commented on pages/advanced/cli-reference/common-operations.mdx
> +### Load a Safe
Inconsistency here:
- Load **a** Safe
- Update (a) Safe

2024-03-22 23:51 UTC, germartinez commented on pages/advanced/cli-reference/common-operations.mdx
> +on the Safe, and at least one should have funds to send transactions.
New line unneeded

2024-03-22 23:53 UTC, germartinez commented on pages/advanced/cli-reference/common-operations.mdx
> +### Send ether
"native coin" instead of "ether"

2024-03-22 23:53 UTC, germartinez commented on pages/advanced/cli-reference/common-operations.mdx
> +### Approve `safe-tx-hash`
```suggestion
### Approve the Safe transaction hash
```

2024-03-22 23:55 UTC, germartinez commented on pages/advanced/cli-reference/common-operations.mdx
> +Send the ERC-20 token from the Safe to another account.
```suggestion
Sends the ERC-20 token from the Safe account to a different one.
```

2024-03-22 23:55 UTC, germartinez commented on pages/advanced/cli-reference/common-operations.mdx
> +Sends a custom transaction from the Safe to a contract. If `--delegate` is set, a `delegatecall` will be triggered.
```suggestion
Sends a custom transaction from the Safe account to a contract. If `--delegate` is set, a `delegatecall` will be triggered.
```

2024-03-22 23:57 UTC, germartinez commented on pages/advanced/cli-installation.mdx
> +# Get Safe CLI
"Safe CLI" or "the Safe CLI"?

2024-03-23 00:00 UTC, germartinez commented on pages/advanced/cli-reference/common-operations.mdx
> +You can create a new Safe by running the following command:
As this is a reference, all the params in the command should be explained in detail

2024-03-23 00:03 UTC, germartinez commented on pages/advanced/cli-reference/tx-service-operations.mdx
> +sign_message [--eip191_message <str>] [--eip712_path <file-path>]
As this is a reference, all the params in the command should be explained in detail. This should apply to all the params in this file

2024-03-23 00:05 UTC, germartinez commented on pages/advanced/cli-reference/tx-service-operations.mdx
> +## Return balance
Inconsistency here:
- Return (the) balance (of a Safe)
- Execute **a** pending transaction
- Sign (a) transaction
- Etc.

2024-03-23 00:34 UTC, germartinez commented on pages/advanced/cli-reference/overview.mdx
> +and mobile app. At least one signer is needed to send transactions to the service. Transactions are *not executed*. It requires *Safe\{Core\} API running on the network*.
```suggestion
At least one signer is needed to send transactions to the service. Transactions are not executed. It requires *Safe\{Core\} API running on the network*.
```

2024-03-23 00:35 UTC, germartinez commented on pages/advanced/cli-reference/overview.mdx
> +Safe CLI comes with the official deterministic Safe contract addresses deployed on multiple chains configured by default. If you want to use your own, you can edit the file `safe_cli/safe_addresses.p
```suggestion
The Safe CLI comes with the official deterministic Safe Smart Account addresses deployed on multiple chains configured by default. If you want to use your own, you can edit the file `safe_cli/safe_addresses.py`
```

2024-03-25 10:07 UTC, louis-md approved these changes
Very nice work 💪

2024-03-25 10:11 UTC, merged

2024-03-25 10:37 UTC, Uxio0 commented on pages/advanced/cli-reference/common-operations.mdx
> +## Update master copy
Agree, we are trying to rename usages of `master copy` to `singleton`