docs(relay-kit): Add Safe4337Pack docs
safe-global/safe-docs pull request #426
Opened 2024-04-02 14:23 UTC by yagopv

2024-04-03 15:07 UTC, germartinez requested changes
So far, this is a review of the code snippets.
I'll continue reviewing this guide

2024-04-03 15:07 UTC, germartinez commented on pages/sdk/relay-kit/guides/how-to-safe4337pack.mdx
> +});
```suggestion
const PRIVATE_KEY = '0x...'

const provider = new ethers.JsonRpcProvider('https://rpc.ankr.com/eth_sepolia')
const signer = new ethers.Wallet(PRIVATE_KEY, provider)
const ethersAdapter = new EthersAdapter({
  ethers,
  signerOrProvider: signer
})
```

2024-04-03 15:07 UTC, germartinez commented on pages/sdk/relay-kit/guides/how-to-safe4337pack.mdx
> +const safeOperation = await safe4337Pack.createTransaction({ transactions });
```suggestion
// Create some transactions
const transaction1 = { to, data, value }
const transaction2 = { to, data, value }

const transactions = [transaction1, transaction2]

// Create the transaction batch bundled in a SafeOperation object
const safeOperation = await safe4337Pack.createTransaction({ transactions })
```

2024-04-03 15:07 UTC, germartinez commented on pages/sdk/relay-kit/guides/how-to-safe4337pack.mdx
> +const signedSafeOperation = await safe4337Pack.signSafeOperation(safeOperation);
```suggestion
const signedSafeOperation = await safe4337Pack.signSafeOperation(safeOperation)
```

2024-04-03 15:07 UTC, germartinez commented on pages/sdk/relay-kit/guides/how-to-safe4337pack.mdx
> +});
```suggestion
const userOperationHash = await safe4337Pack.executeTransaction({
  executable: signedSafeOperation
})
```

2024-04-03 15:07 UTC, germartinez commented on pages/sdk/relay-kit/guides/how-to-safe4337pack.mdx
> +}
```suggestion
let userOperationReceipt = null

while (!userOperationReceipt) {
  await new Promise((resolve) => setTimeout(resolve, 2000)) // Wait 2 seconds before checking the status again
  userOperationReceipt = await safe4337Pack.getUserOperationReceipt(
    userOperationHash
  )
}
```

2024-04-03 15:07 UTC, germartinez commented on pages/sdk/relay-kit/guides/how-to-safe4337pack.mdx
> +);
```suggestion
const userOperationPayload = await safe4337Pack.getUserOperationByHash(
  userOperationHash
)
```

2024-04-03 15:07 UTC, germartinez commented on pages/sdk/relay-kit/reference/safe-4337-pack.md
> +});
```suggestion
const safe4337Pack = await Safe4337Pack.init({
  ethersAdapter,
  rpcUrl,
  bundlerUrl,
  safeModulesVersion,
  customContracts,
  options,
  paymasterOptions
})
```

2024-04-18 12:13 UTC, dasanra commented on pages/sdk/relay-kit/guides/4337-safe.mdx
> +yarn add ethers @safe-global/protocol-kit @safe-global/relay-kit@alpha
We should publish a final version when the docs are ready.

2024-04-18 16:36 UTC, merged