doc: Update Safe Transaction Service sections
safe-global/safe-docs pull request #451
Opened 2024-04-25 11:49 UTC by falvaradorodriguez

Closes https://github.com/safe-global/safe-transaction-service/issues/1783.

2024-04-25 11:51 UTC, falvaradorodriguez commented
To be considered: 

- These changes had been intended by the Core API team for the existing structure previously. Feel free to change anything that is not in the right place.

- It has been very complicated to rethink the services diagram in mermaid, so it is kept in PNG.

In the new "API" overview section there is a "Reference" section that has a broken link to "/core-api/transaction-service-reference".  Where should it lead us?

2024-04-25 14:09 UTC, Uxio0 approved these changes

2024-05-14 16:27 UTC, germartinez requested changes

2024-05-14 16:27 UTC, germartinez commented on pages/advanced/api-overview.md
> +## Integration Flow Safe{Wallet} & Safe{Core}
```suggestion
## Integration Flow for Safe{Wallet} and Safe{Core}
```

2024-05-14 16:49 UTC, germartinez commented on pages/advanced/api-safe-transaction-service.mdx
> +## Running and Maintenance
```suggestion

## Running and Maintenance
```

2024-05-14 17:21 UTC, merged