docs: Update passkeys tutorial
safe-global/safe-docs pull request #536
Opened 2024-07-25 17:16 UTC by louis-md

Update passkeys tutorial with:
- latest packages
- refined UI

2024-07-26 07:07 UTC, tanay1337 commented on pages/home/passkeys-tutorials/safe-passkeys-tutorial.mdx
> +<Callout type='warning' emoji='⚠️'>
Should this be a sub-section called Best practices or something similar instead of a callout?

2024-07-26 10:44 UTC, tanay1337 commented on assets/safe-passkeys-app-1.png
We should write passkeys as "passkeys" when in the middle of a statement and as "Passkeys" when at the beginning for consistency with the rest of the docs.

2024-07-26 10:46 UTC, tanay1337 commented on assets/safe-passkeys-app-2.png
Can we tweak the font color a bit in this view? Personal opinion, but I feel we've overused green in this screen and the deployment pending screen.

2024-07-30 13:47 UTC, tanay1337 requested changes

2024-07-30 13:47 UTC, tanay1337 commented on pages/home/passkeys-tutorials/safe-passkeys-tutorial.mdx
> +You can read more about passkeys in our [overview](../passkeys-overview.mdx) or in the [WebAuthn API documentation](https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API).
```suggestion
You can now integrate passkeys with more transactions and functionalities of the Safe ecosystem. You can read more about passkeys in our [overview](../passkeys-overview.mdx) or in the [WebAuthn API documentation](https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API).
```

2024-07-30 13:47 UTC, tanay1337 commented on pages/home/passkeys-tutorials/safe-passkeys-tutorial.mdx
> +You can now integrate passkeys with more transactions and functionalities of the Safe ecosystem, however please be aware of certain security considerations when dealing with passkeys. We recommend us
```suggestion
Please be mindful of certain security considerations when dealing with passkeys. We recommend using passkeys only in a development environment till all the associated contracts are audited.

For the tutorial's simplicity, we created a 1/1 Safe with a passkey as the sole signer. This is not recommended for production setups. Please always use a combination of passkeys and other authentication methods to ensure the security of your users' assets.
```

2024-07-30 13:47 UTC, tanay1337 commented on pages/home/passkeys-tutorials/safe-passkeys-tutorial.mdx
> +You can now integrate passkeys with more transactions and functionalities of the Safe ecosystem, however please be aware of certain security considerations when dealing with passkeys. We recommend us
Can we also get Niha's input on the wording here?

2024-07-30 16:36 UTC, germartinez commented
- In the Passkeys tutorial (also applies to the ERC-7579 one, but out of scope here), should we use the `<Steps />` component like we do in the guides to separate the diferent sections?
- Be careful with the title and description of this PR, as it also updates the ERC-7579 tutorial, which is not reflected.

2024-07-30 16:44 UTC, niharrs commented
Minor suggestion for the best practices section-
1. Can we put the audit warning at the top of the tutorial in a callout box?
2. Explain in a line or two why 1/1 passkey set up is a bad choice.

Do more with Safe and Passkeys section is all right

2024-07-31 13:31 UTC, merged