Contract docs improvements
safe-global/safe-docs pull request #653
Opened 2024-12-02 16:11 UTC by akshay-ap

Fixes https://github.com/safe-global/developer-experience/issues/243

Changes in PR-

- Improve Overview page for Safe Smart Account

2024-12-04 12:26 UTC, germartinez requested changes

2024-12-04 12:26 UTC, germartinez commented on assets/safe-smart-account-proxy-creation.png
This diagram is duplicated and not used

2024-12-04 16:26 UTC, germartinez commented
I updated the style of the diagrams.
Can we use this version instead?

![Screenshot 2024-12-04 at 16 23 39](https://github.com/user-attachments/assets/e3199d84-a442-4bf6-a7fe-29d63bc1b0ed)

![Screenshot 2024-12-04 at 16 01 09](https://github.com/user-attachments/assets/bd43a36a-42a6-45cd-80a5-73201d29c505)

![Screenshot 2024-12-04 at 16 01 58](https://github.com/user-attachments/assets/9ecd22ae-26c2-44c6-b928-4f0f733d45fa)

![Screenshot 2024-12-04 at 16 24 51](https://github.com/user-attachments/assets/1d317b08-2b6e-414a-9840-38f6d8d05bba)

2025-01-16 08:41 UTC, tanay1337 requested changes
Looks great @akshay-ap. Thoughts on moving the sections in the following order?

- EOAs
- Contract accounts
- EOAs vs. Contract accounts
- Safe smart accounts
...

2025-01-21 09:53 UTC, tanay1337 requested changes
Could you also please run this through Grammarly Pro? Thanks!

2025-01-21 09:53 UTC, tanay1337 commented on pages/advanced/smart-account-overview.mdx
> +## EOAs
Having EOAs as the page title is a bit confusing for me. How about something like `How do Safe Smart Accounts work?` and the EOAs as H2?

2025-01-21 09:53 UTC, tanay1337 commented on pages/advanced/smart-account-overview.mdx
> +EOAs for short are Ethereum accounts that use traditional key pairs. That is, they consist of a single private key that can be used to make transactions and sign messages. If you gain access to that
We should link to the glossary here: https://docs.safe.global/home/glossary#externally-owned-account

2025-01-21 09:53 UTC, tanay1337 commented on pages/advanced/smart-account-overview.mdx
> +The other type of Ethereum accounts are smart contract accounts. Like EOAs, smart contract accounts each have a unique public Ethereum address, and it is impossible to tell them apart from EOAs by lo
We should cross link to https://docs.safe.global/home/glossary#smart-account and aim to reduce redundancy, if possible.

2025-01-21 09:53 UTC, tanay1337 commented on pages/advanced/smart-account-overview.mdx
> +# EOAs vs. Contract Accounts
```suggestion
# Difference between EOAs and Contract Accounts
```

2025-01-21 09:53 UTC, tanay1337 commented on pages/advanced/smart-account-overview.mdx
> +# EOAs vs. Contract Accounts
Only the page title should be H1.

2025-01-21 09:53 UTC, tanay1337 commented on pages/advanced/smart-account-overview.mdx
> +What is the difference between the two different types of accounts on Ethereum: externally owned accounts (EOAs) and contract accounts?
```suggestion
```

2025-01-21 09:53 UTC, tanay1337 commented on pages/advanced/smart-account-overview.mdx
> +## Contract accounts
We should consider if we wanna call them contract accounts or smart accounts as we refer to them as smart account elsewhere.

2025-01-21 09:53 UTC, tanay1337 commented on pages/advanced/smart-account-overview.mdx
> +Safe's **multi-signature** functionality allows you to define a list of owner accounts and a threshold number of accounts required to confirm a transaction. Once the threshold of owner accounts have
```suggestion
Safe's **multi-signature** functionality allows you to define a list of owner accounts and a threshold number of accounts required to confirm a transaction. Once the threshold of owner accounts have confirmed a transaction, the Safe transaction can be executed. Owners can either be EOAs, other smart contract accounts or even a passkey.
```

2025-01-21 09:53 UTC, tanay1337 commented on pages/advanced/smart-account-overview.mdx
> +It is possible to make use of different **Safe Library contracts** to perform complex transactions. A very common example of this is **batched transactions** where multiple simple Ethereum transactio
A bunch of other terms here should be cross-linked to the Glossary.

2025-01-21 09:53 UTC, tanay1337 commented on pages/advanced/smart-account-overview.mdx
> +Many new tokens require wallet contracts to implement callbacks. Token standards like **ERC721** and **ERC1155** allow contracts to immediately react to receiving tokens through these and make it eve
```suggestion
Many new tokens require wallet contracts to implement callbacks. Token standards like **ERC-721** and **ERC-1155** allow contracts to immediately react to receiving tokens through these and make it even possible to reject the transfer altogether.
```

2025-01-21 09:53 UTC, tanay1337 commented on pages/advanced/smart-account-overview.mdx
> +Many new tokens require wallet contracts to implement callbacks. Token standards like **ERC721** and **ERC1155** allow contracts to immediately react to receiving tokens through these and make it eve
We use this format throughout the docs. Could you please update elsewhere in the docs please?

2025-01-21 09:53 UTC, tanay1337 commented on pages/advanced/smart-account-overview.mdx
> +The threshold of owners required to confirm a transaction is also stored in the Safe storage. Owners of a Safe account can change the threshold value as well. A Safe account can have any number of ow
```suggestion
The threshold of owners required to confirm a transaction is also stored in the Safe storage. Owners of a Safe account can change the threshold value as well. A Safe account can have any number of owners and the threshold value can be set to any value between one and the total number of owners.
```

2025-01-24 14:49 UTC, valle-xyz requested changes
Great page so far!

I added some comments to improve the general structure. There is a bigger remark: At this point we should differentiate between Smart Accounts and Multi-Sigs. It seems like these won't mean the exact same things after Pectra with EIP-7702.

In general, I think, this is too much text for the `overview` page. I am not 100% sure on how to improve the structure of the smart account docs yet (let's discuss next week). But I could imagine an introduction page or another page with more explanation text. So basically splitting up this page into one to three other pages.

2025-02-06 16:12 UTC, akshay-ap commented on pages/advanced/smart-account-overview.mdx
> +#### Advanced access management
Recovery is not a core bulit-in feature of Safe Smart Accounts. Users can enable recovery mechanism using modules.

2025-02-06 16:37 UTC, akshay-ap commented on pages/advanced/smart-account-overview.mdx
> +## EOAs
https://github.com/safe-global/safe-docs/pull/653/commits/43f9f5d563e5d25cb184f9eef1dd2f54ad10b99a

2025-02-07 14:25 UTC, valle-xyz requested changes
I really like this version! The writing is clear, concise and beautiful.

We have to make sure to be consistent with our branding, which is, "Safe Smart Accounts". 

Besides that, great work!

2025-02-07 14:25 UTC, valle-xyz commented on pages/advanced/smart-account-overview.mdx
> +The other type of Ethereum account is a [smart contract account](/home/glossary#smart-account). Like EOAs, smart contract accounts each have a unique public Ethereum address, and it is impossible to
Let's use "Smart Accounts" in a capitalized way.

2025-02-07 14:25 UTC, valle-xyz commented on pages/advanced/smart-account-overview.mdx
> +Safe Smart Account is a contract account with multi-signature functionality at its core. It is secure and flexible, and it can be used to manage funds and execute transactions on the Ethereum blockch
... is a Smart Account ...

2025-02-07 14:25 UTC, valle-xyz commented on pages/advanced/smart-account-overview.mdx
> +The Safe Singleton Factory is a contract that deploys all the Safe related contracts. This contract helps to deploy Safe contracts at the same address across different networks and eventually also he
"Safe Smart Account related contracts". (We want to use Safe as a brand, and not to identify Smart Accounts). Also replace "Safe" with "Safe Smart Account" in the next sentence.

2025-02-07 14:25 UTC, valle-xyz commented on pages/advanced/smart-account-overview.mdx
> +Safe Smart Account maintains a [threshold](/home/glossary#threshold), the minimum number of owners required to confirm a transaction before it gets executed. The threshold of owners required to confi
replace Safe with Safe Smart Account, or just say 'in the storage'.

2025-02-07 14:25 UTC, valle-xyz commented on pages/advanced/smart-account-overview.mdx
> +Safe account, being a contract account, does not have a private key to sign transactions, and EVM cannot verify incoming transactions to a contract account. Hence, a contract account has to do the au
Safe Smart Account.

2025-02-07 14:25 UTC, valle-xyz commented on pages/advanced/smart-account-overview.mdx
> +A Safe account verifies if each signer is an owner of the Safe account and verifies the signature based on the signature type. To learn more about the signature types supported by Safe and encoding,
Safe Smart Account

2025-02-07 14:25 UTC, valle-xyz commented on pages/advanced/smart-account-overview.mdx
> +Transactions through a Safe account can be primarily divided into two types:
Safe Smart Account

2025-02-07 14:25 UTC, valle-xyz commented on pages/advanced/smart-account-overview.mdx
> +Safe Smart Account contract provides `execTransaction` function to submit and execute a Safe transaction which is signed by the owners of the Safe account.
Safe Smart Account (at the end)

2025-02-07 14:25 UTC, valle-xyz commented on pages/advanced/smart-account-overview.mdx
> +To execute a transaction with the Safe, the `execTransaction` method needs to be called with the following parameters:
Safe Smart Account

2025-02-07 16:12 UTC, valle-xyz approved these changes
lgtm

2025-02-07 16:29 UTC, germartinez approved these changes

2025-02-07 16:31 UTC, tanay1337 approved these changes

2025-02-07 16:37 UTC, merged